name: Test

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: echo 'Hello there!'
  util-tests:
    runs-on: ubuntu-latest
    needs: greeting
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: install dependencies
        run: npm ci
      - name: test utils
        run: npm run test-utils
